name: CI Debug

on: [push]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # ШАГ 1: Работает?
    - name: Step 1 - Basic test
      run: echo "CI is working"
